name: static_analysis

on:
  pull_request:
    branches:
      - develop
env:
  PHP_EXTENSIONS: 'mbstring, curl, json'
  key: cache-v1 # can be any string, change to clear the extension cache.

jobs:
  static_analysis:
    runs-on: ubuntu-latest
    name: static_analysis
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.1'
        extensions: ${{ env.PHP_EXTENSIONS }}
        tools: composer, psalm
        coverage: none
      env:
        runner: ubuntu-latest # Specify the runner.

    - name: Install dependencies
      run: composer install --prefer-dist --no-dev --ignore-platform-reqs


    - name: 'Run psalm'
      run: 'psalm --php-version=7.0'